import {esc,toast} from './ui.mjs';
import {Audio} from './audio.mjs';
export function createGolfView(root,initial,{send,onExit,now,reduced=false}){
 let state=initial,raf,done=false,angle=-.35,power=.45,busy=false;root.innerHTML=`<div class="game-shell"><div class="game-top"><span class="badge">MINI GOLF CLUB</span><b id="golf-round"></b><button class="back" id="golf-exit">Salir ↗</button></div><section class="golf-panel"><div class="golf-heading"><div><span class="eyebrow">UN GOLPE, MUCHAS POSIBILIDADES</span><h1 id="golf-name"></h1></div><span class="badge" id="golf-clock"></span></div><canvas id="golf-canvas" width="800" height="420" aria-label="Campo de minigolf. Usa los controles de dirección y potencia que están debajo."></canvas><p id="golf-status" aria-live="polite"></p><div class="golf-controls"><label class="field">Dirección <input id="golf-angle" type="range" min="-180" max="180" value="-20"><output id="golf-degrees">−20°</output></label><label class="field">Potencia <input id="golf-power" type="range" min="5" max="100" value="45"><output id="golf-percent">45%</output></label><button class="btn btn-primary" id="golf-shoot">Golpear ↗</button></div><p class="hint">Toca el césped para apuntar o usa las flechas del control de dirección. La línea indica hacia dónde saldrá tu pelota. Hasta 8 golpes · 90 s + tiempo configurado.</p><div class="golf-standing" id="golf-standing"></div></section><section class="feedback" id="golf-result" hidden></section></div>`;
 const $=s=>root.querySelector(s),canvas=$('#golf-canvas'),ctx=canvas.getContext('2d');$('#golf-exit').onclick=onExit;
 $('#golf-angle').oninput=e=>{angle=+e.target.value*Math.PI/180;$('#golf-degrees').textContent=e.target.value+'°';};$('#golf-power').oninput=e=>{power=+e.target.value/100;$('#golf-percent').textContent=e.target.value+'%';};
 canvas.onpointerdown=e=>{const b=state.golf?.[state.me];if(!b)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*800,y=(e.clientY-r.top)/r.height*420;angle=Math.atan2(y-b.y,x-b.x);$('#golf-angle').value=Math.round(angle*180/Math.PI);$('#golf-degrees').textContent=Math.round(angle*180/Math.PI)+'°';};
 $('#golf-shoot').onclick=async()=>{if(busy)return;busy=true;try{await send({type:'golf',roundId:state.question.id,angle,power});Audio.sfx('stroke');}catch(e){toast(e.message);}finally{busy=false;}};
 function update(s){state=s;const q=s.question;if(!q)return;$('#golf-name').textContent=q.course.name;$('#golf-round').textContent=`Hoyo ${s.index+1}/${s.total} · par ${q.course.par}`;$('#golf-standing').innerHTML=s.players.map(p=>`<span class="golf-chip ${p.id===s.me?'mine':''}">${esc(p.avatar)} ${esc(p.name)} · ${s.golf?.[p.id]?.strokes||0} ${s.golf?.[p.id]?.sunk?'⚑':'golpes'}</span>`).join('');const reveal=s.phase==='reveal';$('#golf-result').hidden=!reveal;if(reveal){$('#golf-result').innerHTML=`<h2>${s.myAnswer?.correct?'¡Dentro! Buen recorrido.':'Hoyo completado'}</h2><p>+${s.myAnswer?.points||0} puntos · ${esc(q.explanation)}</p>${s.me===s.hostId?'<button class="btn btn-primary" id="golf-next">Siguiente →</button>':'<p>Esperando al anfitrión…</p>'}`;$('#golf-next')?.addEventListener('click',()=>send({type:'next'}).catch(e=>toast(e.message)));}}
 function draw(){if(done)return;raf=requestAnimationFrame(draw);if(document.hidden||!state.question)return;const q=state.question,c=q.course,b=state.golf?.[state.me],t=now();if(!ctx)return;
 ctx.clearRect(0,0,800,420);ctx.fillStyle='#1e4941';ctx.fillRect(15,22,770,385);ctx.fillStyle='#358569';ctx.fillRect(30,30,740,360);for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#38896c':'#338064';ctx.fillRect(30+i*74,30,74,360);}ctx.strokeStyle='#c3dcac';ctx.lineWidth=6;ctx.strokeRect(30,30,740,360);
 for(const [x,y,w,h]of c.walls){ctx.fillStyle='#143f3b';ctx.fillRect(x+6,y+7,w,h);ctx.fillStyle='#eee0bd';ctx.fillRect(x,y,w,h);ctx.fillStyle='#d4c395';ctx.fillRect(x,y+h-5,w,5);}
 ctx.fillStyle='#163b32';ctx.beginPath();ctx.ellipse(...c.hole,15,12,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fef3d8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(...c.hole);ctx.lineTo(c.hole[0],c.hole[1]-50);ctx.stroke();ctx.fillStyle='#ffe17a';ctx.beginPath();ctx.moveTo(c.hole[0],c.hole[1]-52);ctx.lineTo(c.hole[0]+30,c.hole[1]-43);ctx.lineTo(c.hole[0],c.hole[1]-33);ctx.fill();
 const ready=b&&t>=b.readyAt&&!b.sunk&&b.strokes<8&&state.phase==='playing';if(ready){ctx.setLineDash([6,6]);ctx.strokeStyle='#fbefb6';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x+Math.cos(angle)*(50+power*100),b.y+Math.sin(angle)*(50+power*100));ctx.stroke();ctx.setLineDash([]);}
 for(const p of state.players){const ball=state.golf?.[p.id];if(!ball)continue;let x=ball.x,y=ball.y;if(!reduced&&ball.path?.length&&t<ball.readyAt){const f=Math.max(0,Math.min(ball.path.length-1,(t-ball.at)/Math.max(1,ball.duration)*(ball.path.length-1))),lo=Math.floor(f),hi=Math.min(ball.path.length-1,lo+1),mix=f-lo;[x,y]=ball.path[lo].map((v,i)=>v+(ball.path[hi][i]-v)*mix);}else if(ball.sunk)continue;ctx.globalAlpha=p.id===state.me?1:.4;ctx.fillStyle='#113e35';ctx.beginPath();ctx.ellipse(x+2,y+4,10,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.id===state.me?'#fffef8':p.look?.color||'#f4cc80';ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;}
 $('#golf-shoot').disabled=!ready||busy;$('#golf-clock').textContent=Math.max(0,Math.ceil((state.deadline-t)/1000))+' s';$('#golf-status').textContent=b?.sunk?'⚑ ¡Pelota embocada!':b?.strokes>=8?'Ocho golpes. Espera al grupo.':!ready&&state.phase==='playing'?'La pelota está en movimiento…':`Tu pelota es blanca · ${b?.strokes||0}/8 golpes`;
 }
 update(state);raf=requestAnimationFrame(draw);return {update,destroy(){done=true;cancelAnimationFrame(raf);}};
}
export function createImpostorView(root,initial,{send,onExit,now}){
 let state=initial,phase='',timer,shown=false;const $=s=>root.querySelector(s);
 function update(s){state=s;const spy=s.impostor;if(!spy)return;if(phase!==s.phase){phase=s.phase;shown=false;root.innerHTML=`<div class="game-shell"><div class="game-top"><span class="badge">IMPOSTOR · ${s.index+1}/${s.total}</span><b id="spy-clock"></b><button class="back" id="spy-exit">Salir ↗</button></div><section class="spy-stage"><span class="eyebrow">${spy.impostorCount} IMPOSTOR${spy.impostorCount>1?'ES':''} ENTRE USTEDES</span><h1>${({'spy-role':'Mira tu rol en privado.','spy-clue':'Una pista. Cero spoilers.','spy-vote':'¿Quién está improvisando?','spy-guess':'La última oportunidad.','reveal':'Se reveló el misterio.'})[phase]||'El misterio continúa.'}</h1><p>Categoría: <b>${esc(spy.category)}</b></p><button class="secret-card" id="spy-secret">Toca para ver tu rol</button><div id="spy-action"></div><div class="clue-grid" id="spy-clues"></div><div id="spy-reveal"></div></section></div>`;$('#spy-exit').onclick=onExit;$('#spy-secret').onclick=()=>{shown=!shown;$('#spy-secret').textContent=shown?(spy.role==='impostor'?'Eres impostor · Disimula con la categoría.':'Detective · La palabra es: '+spy.word):'Toca para ver tu rol';};
 if(phase==='spy-role')$('#spy-action').innerHTML='<p class="hint">15 segundos para mirar tu tarjeta. Después, cada persona escribe una pista sin nombrar la palabra. Las pistas se abren todas juntas.</p>';
 if(phase==='spy-clue'){$('#spy-action').innerHTML='<form id="spy-form" class="spy-form"><label class="field">Tu pista (2–60 caracteres)<input id="spy-text" class="input" maxlength="60" minlength="2" required placeholder="Una pista que solo el grupo entenderá…"></label><button class="btn btn-primary">Guardar pista</button></form><p class="hint">Las pistas se mantienen ocultas hasta la votación.</p>';$('#spy-form').onsubmit=e=>{e.preventDefault();send({type:'impostor',kind:'clue',text:$('#spy-text').value}).catch(e=>toast(e.message));};}
 if(phase==='spy-vote')$('#spy-action').innerHTML='<p>Vota una sola vez por otra persona. Se investigan los '+spy.impostorCount+' nombres con más votos. Un empate en el último puesto favorece a los impostores.</p><div class="vote-grid">'+s.players.map(p=>`<button class="vote-card" data-vote="${esc(p.id)}" ${p.id===s.me?'disabled':''}>${esc(p.avatar)} <b>${esc(p.name)}</b></button>`).join('')+'</div>';
 if(phase==='spy-guess'){$('#spy-action').innerHTML=spy.caught.includes(s.me)?'<form id="spy-guess-form" class="spy-form"><label class="field">Un intento para adivinar la palabra<input id="spy-guess" class="input" maxlength="60" required></label><button class="btn btn-primary">Adivinar</button></form>':'<p>Los sospechosos descubiertos tienen 20 segundos para adivinar la palabra. Sin acierto, gana el grupo.</p>';$('#spy-guess-form')?.addEventListener('submit',e=>{e.preventDefault();send({type:'impostor',kind:'guess',text:$('#spy-guess').value}).then(()=>{if($('#spy-guess-form'))$('#spy-guess-form').innerHTML='<p>Intento enviado.</p>';}).catch(e=>toast(e.message));});}
 root.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>send({type:'impostor',kind:'vote',target:b.dataset.vote}).catch(e=>toast(e.message)));
 }
 if(phase==='spy-clue'&&spy.myClue&&$('#spy-form'))$('#spy-form').innerHTML='<p class="notice">✓ Tu pista está guardada. '+esc(spy.myClue)+'</p>';
 if(phase==='spy-vote'&&spy.myVote)root.querySelectorAll('[data-vote]').forEach(b=>{b.disabled=true;b.classList.toggle('selected',b.dataset.vote===spy.myVote);});
 $('#spy-clues').innerHTML=s.players.map(p=>`<div class="clue-card"><b>${esc(p.avatar)} ${esc(p.name)}</b><p>${esc(spy.clues[p.id]||'Pensando…')}</p>${spy.voted.includes(p.id)?'<small>✓ Voto guardado</small>':''}</div>`).join('');
 if(phase==='reveal'){$('#spy-secret').textContent='La palabra era: '+spy.word;$('#spy-reveal').innerHTML=`<div class="feedback"><h2>${spy.outcome?.winner==='cancelled'?'Ronda anulada':spy.outcome?.winner==='detectives'?'¡Ganaron los detectives!':'¡Ganaron los impostores!'}</h2><p>${esc(spy.outcome?.reason)}</p><p>Impostores: ${spy.impostors.map(id=>esc(s.players.find(p=>p.id===id)?.name||'Jugador que salió')).join(', ')}</p><b>+${s.myAnswer?.points||0} puntos</b><p class="hint">800 por victoria de equipo · 200 extra por votar a un impostor.</p>${s.me===s.hostId?'<button class="btn btn-primary" id="spy-next">Siguiente →</button>':'<p>Esperando al anfitrión…</p>'}</div>`;$('#spy-next')?.addEventListener('click',()=>send({type:'next'}).catch(e=>toast(e.message)));}}
 timer=setInterval(()=>{if($('#spy-clock'))$('#spy-clock').textContent=state.deadline?Math.max(0,Math.ceil((state.deadline-now())/1000))+' s':'Pausa';},200);update(state);return {update,destroy(){clearInterval(timer);}};
}
