const WORDS=[['Comida','Empanada'],['Ciudad','Valparaíso'],['Animal','Pingüino'],['Objeto','Paraguas'],['Verano','Piscina'],['Cocina','Cuchara'],['Transporte','Bicicleta'],['Deporte','Minigolf'],['Naturaleza','Volcán'],['Fiesta','Cumpleaños'],['Cine','Palomitas'],['Escuela','Mochila'],['Chile','Completo'],['Invierno','Bufanda'],['Música','Guitarra'],['Playa','Castillo de arena'],['Espacio','Cohete'],['Tecnología','Teclado'],['Dulce','Alfajor'],['Fantasía','Dragón'],['Bebida','Limonada'],['Juego','Ajedrez'],['Campo','Tractor'],['Mar','Faro'],['Bosque','Hongo'],['Viaje','Maleta'],['Fruta','Sandía'],['Profesión','Bombero'],['Montaña','Teleférico'],['Postre','Helado']];
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
export function startImpostor(room,now,rng){
 if(room.players.filter(p=>p.connected).length<3)throw new Error('Impostor necesita al menos 3 personas conectadas.');
 const active=room.players.filter(p=>p.connected).map(p=>p.id),previous=new Set(room.impostor?.impostors||[]);const shuffled=active.map(id=>({id,n:rng()+(previous.has(id)?2:0)})).sort((a,b)=>a.n-b.n).map(x=>x.id);const count=active.length>16?3:active.length>8?2:1;
 const [category,word]=WORDS[(room.seed+room.index)%WORDS.length];room.impostor={category,word,impostors:shuffled.slice(0,count),active,clues:{},votes:{},guesses:{},caught:[],outcome:null};room.phase='spy-role';room.deadline=now+15000;room.startedAt=now;
}
export function spyPublic(room,me){const s=room.impostor;if(!s)return null;const result=['reveal','results'].includes(room.phase);return {category:s.category,role:s.impostors.includes(me)?'impostor':'detective',word:!s.impostors.includes(me)||result?s.word:null,clues:['spy-vote','spy-guess','reveal','results'].includes(room.phase)?s.clues:Object.fromEntries(Object.entries(s.clues).map(([k])=>[k,'✓ Pista guardada'])),myClue:s.clues[me]||null,voted:Object.keys(s.votes),myVote:s.votes[me]||null,impostorCount:s.impostors.length,caught:s.caught,outcome:s.outcome,...(result?{impostors:s.impostors,votes:s.votes,guesses:s.guesses}:{})};}
export function spyAction(room,p,a,now,finish){const s=room.impostor;if(!s||!s.active.includes(p.id)||now>=room.deadline)throw new Error('La fase terminó. Espera la siguiente.');
 if(a.kind==='clue'){if(room.phase!=='spy-clue'||s.clues[p.id])throw new Error('La pista ya está guardada.');const text=String(a.text||'').replace(/[\x00-\x1f]/g,'').trim().slice(0,60);if(text.length<2)throw new Error('Escribe una pista de al menos 2 caracteres.');if(norm(text).includes(norm(s.word)))throw new Error('Da una pista sin escribir la palabra secreta.');s.clues[p.id]=text;if(s.active.every(id=>s.clues[id]||!room.players.find(p=>p.id===id)?.connected)){room.phase='spy-vote';room.deadline=now+45000;}}
 else if(a.kind==='vote'){if(room.phase!=='spy-vote'||s.votes[p.id])throw new Error('Tu voto ya está guardado.');if(a.target===p.id||!s.active.includes(a.target))throw new Error('Elige a otra persona del grupo.');s.votes[p.id]=a.target;if(s.active.every(id=>s.votes[id]||!room.players.find(p=>p.id===id)?.connected))tally(room,now,finish);}
 else if(a.kind==='guess'){if(room.phase!=='spy-guess'||!s.caught.includes(p.id)||s.guesses[p.id])throw new Error('No puedes adivinar en este momento.');const guess=String(a.text||'').trim().slice(0,60);if(!guess)throw new Error('Escribe tu intento.');s.guesses[p.id]=guess;if(norm(guess)===norm(s.word)){finish('impostors',now,'Un impostor descubrió la palabra secreta.');}else if(s.caught.every(id=>s.guesses[id]))finish('detectives',now,'El grupo descubrió a los impostores.');}
 else throw new Error('Acción de impostor inválida.');
}
function tally(room,now,finish){const s=room.impostor,counts={};Object.values(s.votes).forEach(id=>counts[id]=(counts[id]||0)+1);const order=Object.entries(counts).sort((a,b)=>b[1]-a[1]);const n=s.impostors.length,cut=order[n-1]?.[1];if(!cut||order[n]?.[1]===cut){finish('impostors',now,'El empate permitió escapar a los impostores.');return;}s.caught=order.slice(0,n).map(([id])=>id);if(!s.impostors.every(id=>s.caught.includes(id))){finish('impostors',now,'Al menos un impostor evitó ser descubierto.');return;}room.phase='spy-guess';room.deadline=now+20000;}
export function tickSpy(room,now,finish){if(now<room.deadline)return;if(room.phase==='spy-role'){room.phase='spy-clue';room.deadline=now+60000;}else if(room.phase==='spy-clue'){room.phase='spy-vote';room.deadline=now+45000;}else if(room.phase==='spy-vote')tally(room,now,finish);else if(room.phase==='spy-guess')finish('detectives',now,'Los impostores no adivinaron la palabra a tiempo.');}
