import {$,esc,icon,toast,modal} from './ui.mjs';
import {Audio} from './audio.mjs';
import {parseVideo,parseLRC} from './karaoke-core.mjs';
const warmup=[{t:0,text:'♪ Prepárate… 1, 2, 3, 4'},{t:4,text:'Hello, hello, let’s sing together!'},{t:8,text:'Clap your hands, we feel much better.'},{t:12,text:'One small step, one happy sound,'},{t:16,text:'Share your voice with friends around.'},{t:20,text:'Hello, hello, here we go!'},{t:24,text:'Sing it loud, or sing it slow.'},{t:28,text:'Every voice can join the song,'},{t:32,text:'Here with friends is where we belong.'},{t:36,text:'¡Muy bien! ✨'}];
let ytPromise;
function loadYT(){if(window.YT?.Player)return Promise.resolve();if(ytPromise)return ytPromise;ytPromise=new Promise((resolve,reject)=>{let done=false;const timeout=setTimeout(()=>{if(!done){done=true;ytPromise=null;reject(new Error('YouTube no respondió. Puedes usar una pista local o intentarlo nuevamente.'));}},12000);const prev=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{prev?.();if(!done){done=true;clearTimeout(timeout);resolve();}};let s=document.getElementById('studio-yt-api');if(s)s.remove();s=document.createElement('script');s.id='studio-yt-api';s.src='https://www.youtube.com/iframe_api';s.onerror=()=>{if(!done){done=true;clearTimeout(timeout);ytPromise=null;reject(new Error('No se pudo conectar con YouTube.'));}};document.head.appendChild(s);});return ytPromise;}
export function createKaraoke(root,{room=null,send=null,onExit=()=>{},onGroup=()=>{}}={}){
 Audio.stop();let disposed=false,state=room?.karaoke||{queue:[],now:null,playing:false,revision:0},host=!room||room.hostId===room.me,me=room?.me||'local',player,videoId=null,ytLoading=false,stream,micCtx,micRaf,localUrl=null,lyrics=[],warmCtx,warmTimer,warmStart=0,localMode=false,musicNotes=[];
 root.innerHTML=`<div class="back-row"><button class="back" id="studio-back">← Volver</button><span class="badge">${room?'Sala '+esc(room.code)+' · hasta 30':'Escenario personal'}</span></div><div class="section-head"><div><h1>Karaoke Studio<span style="color:#bba1cf">.</span></h1><p>Tu canción. Tu turno. Tu momento.</p></div>${!room?'<button class="btn btn-outline" id="studio-group">Invitar al grupo ↗</button>':''}</div><div class="studio-grid"><div><section class="studio-stage"><div class="studio-label">● ON STAGE · GAME QUIZ</div><h2 id="song-title">El escenario es tuyo</h2><p id="singer-name">Añade una canción a la cola para empezar.</p><div id="video-area" class="youtube-wrap"><div class="youtube-placeholder">${icon('mic')}<p>Enlaces de YouTube, pistas propias<br>o un calentamiento con letra incluida.</p></div></div><div id="lyrics-area" hidden><div class="lyrics-current" id="lyric-now"></div><div class="lyrics-next" id="lyric-next"></div><audio id="local-audio" class="local-audio" controls></audio></div><p id="studio-error" class="karaoke-alert" role="status"></p><div class="studio-controls" id="studio-controls"><button id="studio-play">▶ Reproducir / pausar</button><button id="studio-next">Siguiente →</button><button id="studio-full" aria-label="Pantalla completa">⛶</button></div><div class="mic-meter" id="mic-meter" hidden>${'<i></i>'.repeat(16)}</div></section><div class="studio-tools" id="studio-tools"><button class="btn btn-white" id="warmup">✦ Calentamiento en inglés</button><button class="btn btn-white" id="load-audio">＋ Pista y letra LRC</button><button class="btn btn-white" id="mic-test">🎙 Probar micrófono</button></div><p class="hint">El micrófono solo muestra el nivel de tu voz: no graba ni envía audio. La pantalla del anfitrión reproduce las canciones; los invitados administran sus solicitudes.</p></div><section class="panel"><div class="section-head"><h2>Próximos turnos</h2><span class="badge" id="queue-count">0</span></div><div class="queue" id="queue"></div><form id="song-form"><label class="field">Enlace de YouTube<input class="input" id="song-url" type="url" placeholder="https://youtu.be/…" required></label><label class="field">Canción<input class="input" id="song-name" maxlength="90" placeholder="Título para identificarla" required></label>${!room?'<label class="field">¿Quién canta?<input class="input" id="song-singer" maxlength="20" placeholder="Tu nombre" required></label>':''}<button class="btn btn-primary full" type="submit">Añadir a la cola ＋</button><p class="hint">Puedes añadir hasta 3 canciones por persona en una sala. Algunos videos no permiten reproducción integrada.</p></form></section></div>`;
 function error(t){if(!disposed)$('#studio-error').textContent=t;}
 function stopWarm(){clearInterval(warmTimer);warmTimer=null;musicNotes.forEach(o=>{try{o.stop();}catch{}});musicNotes=[];warmCtx?.close().catch(()=>{});warmCtx=null;}
 function stopLocal(){stopWarm();const a=$('#local-audio');if(a){a.pause();a.removeAttribute('src');a.load();}if(localUrl){URL.revokeObjectURL(localUrl);localUrl=null;}localMode=false;}
 function lineAt(t){let i=lyrics.findLastIndex(l=>l.t<=t);$('#lyric-now').textContent=i<0?'♪ Espera la entrada…':lyrics[i].text;$('#lyric-next').textContent=lyrics[i+1]?.text||'';}
 async function command(cmd){try{if(send){await send({type:'karaoke',...cmd});return true;}if(cmd.kind==='add'){if(state.queue.length>=50)throw new Error('La cola está llena.');state.queue.push({id:crypto.randomUUID?.()||String(Date.now()),video:cmd.video,title:cmd.title,singer:cmd.singer,by:'local'});}if(cmd.kind==='next'){stopLocal();state.now=state.queue.shift()||null;state.playing=!!state.now;}if(cmd.kind==='toggle')state.playing=!state.playing;if(cmd.kind==='remove')state.queue=state.queue.filter(q=>q.id!==cmd.item);if(cmd.kind==='move'){const i=state.queue.findIndex(q=>q.id===cmd.item);if(i>0)[state.queue[i-1],state.queue[i]]=[state.queue[i],state.queue[i-1]];}state.revision++;await render();return true;}catch(e){error(e.message);return false;}}
 async function video(){if(!host||localMode)return;const item=state.now;if(!item){try{player?.stopVideo();}catch{}videoId=null;return;}if(item.video!==videoId){stopLocal();$('#lyrics-area').hidden=true;$('#video-area').hidden=false;videoId=item.video;error('');try{if(!player){if(ytLoading)return;ytLoading=true;await loadYT();if(disposed)return;$('#video-area').innerHTML='<div id="studio-player"></div>';player=new window.YT.Player('studio-player',{width:'100%',height:'100%',videoId:state.now?.video,playerVars:{playsinline:1,origin:location.origin,rel:0},events:{onReady:()=>{ytLoading=false;player.setVolume(65);if(state.playing)player.playVideo();},onAutoplayBlocked:()=>error('Toca ▶ para permitir la reproducción en esta pantalla.'),onError:e=>error(({2:'El enlace no es válido.',5:'El video no pudo cargarse.',100:'El video no está disponible.',101:'Este video no permite reproducción integrada.',150:'Este video no permite reproducción integrada.',153:'YouTube no pudo verificar el sitio. Usa el juego desde HTTP o HTTPS.'})[e.data]||'No se pudo reproducir. Prueba otra canción.'),onStateChange:e=>{if(e.data===0)error('Canción terminada. Toca Siguiente para dar paso al próximo turno.');}}});}else player.loadVideoById(item.video);}catch(e){ytLoading=false;videoId=null;error(e.message);}}else if(player){try{state.playing?player.playVideo():player.pauseVideo();}catch{}}}
 async function render(){if(disposed)return;$('#queue-count').textContent=state.queue.length;$('#queue').innerHTML=state.queue.length?state.queue.map((q,i)=>`<div class="queue-item"><span>${i+1}</span><div><b>${esc(q.title)}</b><small>${esc(q.singer)}</small></div>${host?`<button data-up="${esc(q.id)}" aria-label="Subir canción">↑</button><button data-remove="${esc(q.id)}" aria-label="Quitar canción">×</button>`:''}</div>`).join(''):'<p class="muted">La primera canción puede ser la tuya. ✨</p>';$('#studio-controls').hidden=!host;$('#studio-tools').hidden=!host;if(!localMode){$('#song-title').textContent=state.now?.title||'El escenario es tuyo';$('#singer-name').textContent=state.now?'Canta: '+state.now.singer:'Añade una canción y toca Siguiente para empezar.';}if(!host)$('#video-area').innerHTML=`<div class="youtube-placeholder">${icon('mic')}<p>La canción suena en la pantalla del anfitrión.<br>Añade tu canción para reservar un turno.</p></div>`;await video();}
 $('#studio-back').onclick=onExit;if($('#studio-group'))$('#studio-group').onclick=onGroup;
 $('#song-form').onsubmit=async e=>{e.preventDefault();const vid=parseVideo($('#song-url').value);if(!vid){error('Pega un enlace de YouTube válido.');return;}const ok=await command({kind:'add',video:vid,title:$('#song-name').value,singer:$('#song-singer')?.value||''});if(ok)$('#song-form').reset();};
 $('#queue').onclick=e=>{const b=e.target.closest('button');if(b?.dataset.up)command({kind:'move',item:b.dataset.up});if(b?.dataset.remove)command({kind:'remove',item:b.dataset.remove});};
 $('#studio-next').onclick=()=>{stopLocal();command({kind:'next'});};
 $('#studio-play').onclick=()=>{if(localMode){if(warmCtx){if(warmCtx.state==='running')warmCtx.suspend();else warmCtx.resume();}else{const a=$('#local-audio');a.paused?a.play().catch(e=>error(e.message)):a.pause();}return;}if(!state.now){command({kind:'next'});return;}if(player?.getPlayerState?.()!==1){state.playing=false;}command({kind:'toggle'});};
 $('#studio-full').onclick=()=>{const p=root.querySelector('.studio-stage');if(document.fullscreenElement)document.exitFullscreen?.();else p.requestFullscreen?.().catch(()=>toast('La pantalla completa no está disponible en este navegador.'));};
 $('#warmup').onclick=()=>{stopLocal();try{player?.pauseVideo();warmCtx=new(window.AudioContext||window.webkitAudioContext)();warmCtx.resume();localMode=true;lyrics=warmup;$('#video-area').hidden=true;$('#lyrics-area').hidden=false;$('#local-audio').hidden=true;$('#song-title').textContent='Sing together';$('#singer-name').textContent='Calentamiento original · 38 segundos · nivel A1';warmStart=warmCtx.currentTime;const chords=[[60,64,67],[57,60,64],[53,57,60],[55,59,62]];for(let i=0;i<76;i++){const c=chords[Math.floor(i/8)%4],o=warmCtx.createOscillator(),g=warmCtx.createGain(),t=warmStart+i*.5;o.type='triangle';o.frequency.value=440*2**((c[i%3]-69)/12);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.08,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.4);o.connect(g).connect(warmCtx.destination);o.start(t);o.stop(t+.45);musicNotes.push(o);}warmTimer=setInterval(()=>{if(!warmCtx)return;const t=warmCtx.currentTime-warmStart;lineAt(t);if(t>=38){stopWarm();error('¡Calentamiento terminado! Puedes repetirlo o elegir una canción.');}},100);error('');}catch{error('El audio no está disponible en este navegador.');}};
 $('#load-audio').onclick=()=>{modal('Tu pista, tu letra',`<p class="muted">Carga una pista de audio y, si tienes, una letra sincronizada en formato LRC. Los archivos permanecen en este dispositivo.</p><label class="field">Pista de audio<input id="audio-file" class="input" type="file" accept="audio/*"></label><label class="field">Letra LRC (opcional)<input id="lrc-file" class="input" type="file" accept=".lrc,text/plain"></label><button class="btn btn-primary full" id="use-local">Preparar pista</button><p class="error-text" id="local-error"></p>`);$('#use-local').onclick=async()=>{const f=$('#audio-file').files[0],l=$('#lrc-file').files[0];if(!f){$('#local-error').textContent='Elige una pista de audio.';return;}if(f.size>150*1024*1024){$('#local-error').textContent='Usa una pista menor a 150 MB.';return;}if(l&&l.size>1024*1024){$('#local-error').textContent='La letra LRC debe ser menor a 1 MB.';return;}const parsed=l?parseLRC(await l.text()):[];if(l&&!parsed.length){$('#local-error').textContent='No encontramos tiempos válidos. Ejemplo: [00:05.00] Primera línea';return;}stopLocal();try{player?.pauseVideo();}catch{}localMode=true;lyrics=parsed;localUrl=URL.createObjectURL(f);const a=$('#local-audio');a.src=localUrl;a.hidden=false;a.ontimeupdate=()=>lineAt(a.currentTime);a.onerror=()=>error('No se pudo leer esta pista. Prueba un archivo MP3 o WAV.');$('#video-area').hidden=true;$('#lyrics-area').hidden=false;$('#song-title').textContent=f.name;$('#singer-name').textContent='Pista local · lista para reproducir';$('#lyric-now').textContent=lyrics.length?'Toca reproducir para comenzar.':'♪ Tu pista está preparada';$('#lyric-next').textContent='';$('#dialog').close();};};
 function stopMic(){stream?.getTracks().forEach(t=>t.stop());stream=null;cancelAnimationFrame(micRaf);micCtx?.close().catch(()=>{});micCtx=null;$('#mic-meter').hidden=true;$('#mic-test').textContent='🎙 Probar micrófono';}
 $('#mic-test').onclick=async()=>{if(stream){stopMic();return;}try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('El micrófono requiere HTTPS o localhost y un navegador compatible.');const s=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(disposed){s.getTracks().forEach(t=>t.stop());return;}stream=s;micCtx=new(window.AudioContext||window.webkitAudioContext)();await micCtx.resume();const analyser=micCtx.createAnalyser();analyser.fftSize=256;micCtx.createMediaStreamSource(stream).connect(analyser);const data=new Uint8Array(analyser.frequencyBinCount);$('#mic-meter').hidden=false;$('#mic-test').textContent='■ Apagar micrófono';function frame(){if(!stream||disposed)return;analyser.getByteFrequencyData(data);$('#mic-meter').querySelectorAll('i').forEach((b,i)=>b.style.height=(4+data[i*3]/255*30)+'px');micRaf=requestAnimationFrame(frame);}frame();error('Micrófono activo solo para medir volumen. No se graba ni se transmite.');}catch(e){error(e.name==='NotAllowedError'?'No se concedió acceso al micrófono. Puedes seguir cantando sin activarlo.':e.message);}};
 render();return {update(r){const wasHost=host;room=r;host=r.hostId===r.me;if(wasHost&&!host){stopLocal();stopMic();try{player?.destroy();}catch{}player=null;videoId=null;}me=r.me;state=r.karaoke;render();},destroy(){disposed=true;stopLocal();stopMic();try{player?.destroy();}catch{}}};
}
