export const BACH_CATEGORIES=['Nombre o apellido','País o ciudad','Fruta o verdura','Color o cosa','Animal o ave','Marca o TV'];
export const LETTERS='ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'.split('');
export const normAnswer=s=>String(s||'').trim().toLocaleLowerCase('es').replace(/ñ/g,'\u0001').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\u0001/g,'ñ').replace(/[^a-zñ0-9 ]/g,'').replace(/\s+/g,' ');
const shuffle=(a,rng)=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
export function makeBingoCard(rng){const grid=Array.from({length:3},()=>Array(9).fill(null));const sizes=Array(9).fill(1);for(const col of shuffle([0,1,2,3,4,5,6,7,8],rng).slice(0,6))sizes[col]++;const left=[5,5,5];for(const col of shuffle([0,1,2,3,4,5,6,7,8],rng)){const rows=[0,1,2].sort((a,b)=>left[b]-left[a]);const pick=rows.slice(0,sizes[col]).sort();const first=col===0?1:col*10,last=col===8?90:col*10+9;const ns=shuffle(Array.from({length:last-first+1},(_,i)=>first+i),rng).slice(0,sizes[col]).sort((a,b)=>a-b);pick.forEach((row,i)=>{grid[row][col]=ns[i];left[row]--;});}return grid;}
export function startBingo(room,now,rng){room.bingo={bag:shuffle(Array.from({length:90},(_,i)=>i+1),rng),called:[],cards:Object.fromEntries(room.players.map(p=>[p.id,makeBingoCard(rng)])),marks:Object.fromEntries(room.players.map(p=>[p.id,[]])),lineWinner:null,winner:null,lastDraw:0};room.phase='bingo';room.startedAt=now;room.deadline=0;}
export function bingoPublic(room,me){const b=room.bingo;if(!b)return null;return {called:b.called,card:b.cards[me],marks:b.marks[me]||[],lineWinner:b.lineWinner,winner:b.winner,remaining:b.bag.length,marked:room.players.map(p=>({id:p.id,count:b.marks[p.id]?.length||0}))};}
export function bingoAction(room,p,a,now,finish){const b=room.bingo;if(room.phase!=='bingo'||!b)throw new Error('El bingo no está abierto.');
 if(a.kind==='draw'){if(p.id!==room.hostId)throw new Error('Solo el anfitrión saca bolitas.');if(now-b.lastDraw<2000&&b.called.length)throw new Error('Espera dos segundos entre bolitas.');if(!b.bag.length)throw new Error('Ya salieron los 90 números. Revisa tu cartón.');b.called.push(b.bag.pop());b.lastDraw=now;return;}
 if(a.kind==='mark'){const n=+a.number;if(!b.cards[p.id]?.flat().includes(n)||!b.called.includes(n))throw new Error('Solo puedes marcar números de tu cartón que ya salieron.');const arr=b.marks[p.id];b.marks[p.id]=arr.includes(n)?arr.filter(x=>x!==n):[...arr,n];return;}
 if(a.kind==='line'||a.kind==='bingo'){const marked=new Set(b.marks[p.id]),complete=row=>row.filter(Boolean).every(n=>marked.has(n)&&b.called.includes(n));if(a.kind==='line'){if(b.lineWinner)throw new Error('La primera línea ya tiene ganador.');if(!b.cards[p.id].some(complete))throw new Error('Aún no tienes una fila completa marcada.');b.lineWinner=p.id;p.score+=300;}else{if(!b.cards[p.id].every(complete))throw new Error('Todavía faltan números por marcar.');b.winner=p.id;p.score+=1000;p.correct++;finish(now);}return;}
 throw new Error('Acción de bingo inválida.');
}
export function startBach(room,now,rng){const omitted=new Set(room.settings.omitLetters||['K','Ñ','Q','W','X','Y','Z']);let available=LETTERS.filter(l=>!omitted.has(l)&&!room.bachUsedLetters?.includes(l));if(!available.length){room.bachUsedLetters=[];available=LETTERS.filter(l=>!omitted.has(l));}if(!available.length)throw new Error('Deja al menos una letra disponible.');const letter=available[Math.floor(rng()*available.length)];room.bachUsedLetters??=[];room.bachUsedLetters.push(letter);room.bach={letter,drafts:Object.fromEntries(room.players.map(p=>[p.id,{values:Array(6).fill(''),noSe:Array(6).fill(false),revision:0}])),votes:{},reviewed:[],stopBy:null,scoreRows:null,reviewDeadline:0};room.phase='bach-writing';room.startedAt=now;room.deadline=now+60000;}
export function isComplete(draft,letter){return draft?.values.every((v,i)=>!draft.noSe[i]&&normAnswer(v).startsWith(normAnswer(letter))&&normAnswer(v).length>=1);}
export function bachPublic(room,me){const b=room.bach;if(!b)return null;const writing=room.phase==='bach-writing';return {roundId:room.rounds[room.index]?.id,letter:b.letter,categories:BACH_CATEGORIES,mine:b.drafts[me],stopBy:b.stopBy,reviewed:b.reviewed,reviewDeadline:b.reviewDeadline,progress:room.players.map(p=>({id:p.id,count:b.drafts[p.id]?.values.filter((v,i)=>v.trim()&&!b.drafts[p.id].noSe[i]).length||0})),...(!writing?{drafts:b.drafts,votes:b.votes,scoreRows:b.scoreRows}:{})};}
export function calculateBach(room){const b=room.bach,rows=room.players.map(p=>({id:p.id,name:p.name,cells:[],total:0}));for(let col=0;col<6;col++){
 const valid=new Map(),noAnswer=room.players.some(p=>{const d=b.drafts[p.id];return !d||d.noSe[col]||!normAnswer(d.values[col]);});
 for(const p of room.players){const d=b.drafts[p.id],value=normAnswer(d?.values[col]),votes=b.votes[p.id+':'+col]||{},eligible=room.players.filter(x=>x.id!==p.id),yes=eligible.filter(x=>votes[x.id]===true).length,no=eligible.filter(x=>votes[x.id]===false).length,rejected=no>yes&&no>=Math.ceil(eligible.length/2);valid.set(p.id,!!value&&!d?.noSe[col]&&value.startsWith(normAnswer(b.letter))&&!rejected);}
 for(const row of rows){const d=b.drafts[row.id],value=normAnswer(d?.values[col]),accepted=valid.get(row.id),duplicates=accepted?rows.filter(x=>valid.get(x.id)&&normAnswer(b.drafts[x.id]?.values[col])===value).length:0,base=accepted?(duplicates>1?50:100):0,bonus=accepted&&noAnswer?10:0;row.cells.push({value:d?.values[col]||'',noSe:!!d?.noSe[col],accepted,duplicates,base,bonus,points:base+bonus});row.total+=base+bonus;}
 }return rows;}
export function bachAction(room,p,a,now,score){const b=room.bach;if(!b)throw new Error('No hay ronda de bachillerato.');if(a.roundId!==room.rounds[room.index]?.id)throw new Error('La ronda cambió.');
 if(a.kind==='draft'||a.kind==='stop'){if(room.phase!=='bach-writing'||now>=room.deadline)throw new Error('El tiempo terminó.');if(!Array.isArray(a.values)||a.values.length!==6||!Array.isArray(a.noSe)||a.noSe.length!==6)throw new Error('Completa las seis casillas.');const revision=Number(a.revision)||0;if(revision>b.drafts[p.id].revision)b.drafts[p.id]={values:a.values.map(v=>String(v||'').replace(/[\x00-\x1f]/g,'').trim().slice(0,60)),noSe:a.noSe.map(Boolean),revision};if(a.kind==='stop'){if(!isComplete(b.drafts[p.id],b.letter))throw new Error('STOP necesita seis respuestas con la letra elegida y sin «No sé».');if(!b.stopBy){b.stopBy=p.id;room.deadline=Math.min(room.deadline,now+10000);}}return;}
 if(room.phase!=='bach-review')throw new Error('Esta acción pertenece a la revisión.');
 if(a.kind==='vote'){if(a.player===p.id||!room.players.some(x=>x.id===a.player)||!Number.isInteger(a.column)||a.column<0||a.column>5||typeof a.valid!=='boolean')throw new Error('Elige una respuesta de otro jugador.');const key=a.player+':'+a.column;b.votes[key]??={};b.votes[key][p.id]=a.valid;b.reviewed=b.reviewed.filter(id=>id!==p.id);}
 else if(a.kind==='noSe'){if(!Number.isInteger(a.column)||a.column<0||a.column>5)throw new Error('Casilla inválida.');b.drafts[p.id].noSe[a.column]=!b.drafts[p.id].noSe[a.column];b.reviewed=[];}
 else if(a.kind==='reviewed'){for(const other of room.players)if(other.id!==p.id)for(let col=0;col<6;col++){const key=other.id+':'+col;b.votes[key]??={};if(b.votes[key][p.id]===undefined)b.votes[key][p.id]=true;}if(!b.reviewed.includes(p.id))b.reviewed.push(p.id);}
 else if(a.kind==='finish'){if(p.id!==room.hostId)throw new Error('Solo el anfitrión cierra la revisión.');if(now<b.reviewDeadline&&!room.players.filter(p=>p.connected).every(p=>b.reviewed.includes(p.id)))throw new Error('Falta que el grupo termine de revisar.');score(now);}
 else throw new Error('Acción de bachillerato inválida.');
}
export function tickBach(room,now,score){if(room.phase==='bach-writing'&&now>=room.deadline){room.phase='bach-review';room.bach.reviewDeadline=now+90000;room.deadline=0;}else if(room.phase==='bach-review'&&now>=room.bach.reviewDeadline)score(now);}
