import {esc,toast} from './ui.mjs';
import {Audio} from './audio.mjs';
import {isComplete,normAnswer} from './party-games.mjs';
export function createBingoView(root,initial,{send,onExit}){let state=initial;const $=s=>root.querySelector(s);root.innerHTML=`<div class="game-shell"><div class="game-top"><span class="badge">BINGO DEL CLUB · 90 BOLITAS</span><button id="bingo-exit" class="back">Salir ↗</button></div><section class="bingo-hero"><div><span class="eyebrow">CADA NÚMERO TE ACERCA</span><h1>Tu próximo bingo.</h1><p>15 números · 3 filas · mucha atención</p></div><div class="bingo-ball" id="bingo-ball">?</div></section><section class="panel"><div class="section-head"><h2>Tu cartón personal</h2><span id="bingo-marked" class="badge"></span></div><div class="bingo-card" id="bingo-card"></div><div class="dialog-actions"><button class="btn btn-outline" id="bingo-line">¡Línea! · 300 pts</button><button class="btn btn-primary" id="bingo-claim">¡BINGO! · 1000 pts</button></div><p id="bingo-note" class="hint"></p></section><section class="panel" style="margin-top:20px"><div class="section-head"><h2>Ya salieron</h2><button class="btn btn-primary" id="bingo-draw">Sacar bolita</button></div><div class="bingo-called" id="bingo-called"></div><p id="bingo-count" class="hint"></p></section></div>`;$('#bingo-exit').onclick=onExit;
 async function act(a){try{await send({type:'bingo',...a});Audio.sfx(a.kind==='bingo'?'win':a.kind==='line'?'correct':'tap');}catch(e){toast(e.message);}}
 $('#bingo-draw').onclick=()=>act({kind:'draw'});$('#bingo-line').onclick=()=>act({kind:'line'});$('#bingo-claim').onclick=()=>act({kind:'bingo'});root.onclick=e=>{const b=e.target.closest('[data-ball]');if(b)act({kind:'mark',number:+b.dataset.ball});};
 function update(s){state=s;const b=s.bingo;if(!b)return;$('#bingo-ball').textContent=b.called.at(-1)||'?';$('#bingo-marked').textContent=b.marks.length+'/15 marcados';$('#bingo-card').innerHTML=b.card.flat().map(n=>n?`<button class="bingo-cell ${b.marks.includes(n)?'marked':''} ${b.called.includes(n)?'available':''}" data-ball="${n}" aria-pressed="${b.marks.includes(n)}" ${!b.called.includes(n)?'disabled':''}>${n}</button>`:'<span class="bingo-cell empty">✦</span>').join('');$('#bingo-called').innerHTML=Array.from({length:90},(_,i)=>`<span class="${b.called.includes(i+1)?'drawn':''}">${i+1}</span>`).join('');$('#bingo-draw').hidden=s.me!==s.hostId;$('#bingo-draw').disabled=!b.remaining;$('#bingo-line').disabled=!!b.lineWinner;$('#bingo-note').textContent=b.lineWinner?'Primera línea: '+s.players.find(p=>p.id===b.lineWinner)?.name:'Toca un número cuando salga. Puedes desmarcarlo tocándolo otra vez. Solo la primera línea tiene premio.';$('#bingo-count').textContent=b.called.length+' números sorteados · '+b.remaining+' por salir';}
 update(state);return {update,destroy(){root.onclick=null;}};
}
export function createBachView(root,initial,{send,onExit,now}){let state=initial,phase='',category=0,draft,revision=0,debounce,timer,disposed=false;const $=s=>root.querySelector(s);
 const call=a=>send({type:'bach',roundId:state.bach.roundId,...a});
 function controls(){if(!$('#bach-stop'))return;$('#bach-stop').disabled=!isComplete(draft,state.bach.letter)||!!state.bach.stopBy;for(let i=0;i<6;i++){const input=$('[data-bach-input="'+i+'"]'),btn=$('[data-nose="'+i+'"]');input.disabled=draft.noSe[i];btn.classList.toggle('selected',draft.noSe[i]);btn.textContent=draft.noSe[i]?'↶ Responder':'No sé';input.classList.toggle('invalid-initial',!!draft.values[i]&&!normAnswer(draft.values[i]).startsWith(normAnswer(state.bach.letter)));}}
 async function save(kind='draft'){clearTimeout(debounce);if(disposed||phase!=='bach-writing')return;try{await call({kind,values:[...draft.values],noSe:[...draft.noSe],revision:++revision});if($('#bach-saved'))$('#bach-saved').textContent='✓ Respuestas guardadas';}catch(e){if($('#bach-saved'))$('#bach-saved').textContent=e.message;if(kind==='stop')toast(e.message);}}
 function update(s){state=s;const b=s.bach;if(!b)return;
 if(phase!==s.phase){phase=s.phase;clearTimeout(debounce);root.innerHTML=`<div class="game-shell bach-shell"><div class="game-top"><span class="badge">BACHILLERATO · RONDA ${s.index+1}/${s.total}</span><button class="back" id="bach-exit">Salir ↗</button></div><section class="bach-hero"><div><span class="eyebrow">UNA LETRA. SEIS IDEAS.</span><h1>${phase==='bach-writing'?'¡A pensar rápido!':phase==='bach-review'?'El jurado somos todos.':'Cada respuesta cuenta.'}</h1><p id="bach-status"></p></div><div class="letter-orb">${esc(b.letter)}</div><strong id="bach-clock"></strong></section><div id="bach-content"></div></div>`;$('#bach-exit').onclick=onExit;
 if(phase==='bach-writing'){draft=structuredClone(b.mine);revision=draft.revision||0;$('#bach-content').innerHTML=`<div class="bach-fields">${b.categories.map((c,i)=>`<label class="bach-field"><span><b>${i+1}</b> ${esc(c)}</span><div><input class="input" data-bach-input="${i}" maxlength="60" autocomplete="off" autocapitalize="words" placeholder="Empieza con ${esc(b.letter)}…" value="${esc(draft.values[i])}"><button type="button" class="no-se" data-nose="${i}">No sé</button></div></label>`).join('')}</div><div class="stop-bar"><span id="bach-saved" class="hint">Tus respuestas se guardan mientras escribes.</span><button class="stop-button" id="bach-stop">STOP</button></div><p class="hint">Solo puedes parar con seis respuestas que empiecen con ${esc(b.letter)} y sin «No sé». Quedarán hasta 10 segundos; la ronda dura como máximo un minuto.</p><div class="bach-progress" id="bach-progress"></div>`;root.querySelectorAll('[data-bach-input]').forEach(input=>input.oninput=e=>{draft.values[+e.target.dataset.bachInput]=e.target.value;controls();if($('#bach-saved'))$('#bach-saved').textContent='Guardando…';clearTimeout(debounce);debounce=setTimeout(()=>save(),160);});root.querySelectorAll('[data-nose]').forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.nose;draft.noSe[i]=!draft.noSe[i];controls();save();});$('#bach-stop').onclick=()=>save('stop');controls();}}
 if(phase==='bach-writing'){if($('#bach-progress'))$('#bach-progress').innerHTML=b.progress.map(p=>`<span>${esc(s.players.find(x=>x.id===p.id)?.name)} <b>${p.count}/6</b></span>`).join('');$('#bach-status').textContent=b.stopBy?'STOP de '+s.players.find(p=>p.id===b.stopBy)?.name+' · ¡Últimos segundos!':'60 segundos desde el inicio. Las respuestas del resto están ocultas.';controls();}
 if(phase==='bach-review')review();if(phase==='bach-score')scores();
 }
 function review(){const b=state.bach;$('#bach-status').textContent='Revisa una categoría a la vez. Acepta o rechaza las respuestas del resto.';$('#bach-content').innerHTML=`<div class="tabs bach-tabs">${b.categories.map((c,i)=>`<button class="chip ${i===category?'active':''}" data-category="${i}">${i+1}. ${esc(c)}</button>`).join('')}</div><section class="panel"><h2>${esc(b.categories[category])}</h2><div class="bach-review-list">${state.players.map(p=>{const d=b.drafts[p.id],votes=b.votes[p.id+':'+category]||{},own=p.id===state.me,value=d?.values[category]||'',skip=d?.noSe[category]||!value;return `<article class="bach-review-row"><div><b>${esc(p.avatar)} ${esc(p.name)} ${own?'(tú)':''}</b><p class="${skip?'muted':''}">${d?.noSe[category]?'No sé':esc(value)||'Sin respuesta'}</p></div>${own?`<button class="chip" id="review-nose">${d?.noSe[category]?'↶ Revertir «No sé»':'Marcar «No sé»'}</button>`:`<div class="vote-actions"><button data-judge="${esc(p.id)}" data-valid="true" class="${votes[state.me]===true?'selected':''}" ${skip?'disabled':''}>✓ Válida</button><button data-judge="${esc(p.id)}" data-valid="false" class="${votes[state.me]===false?'rejected':''}" ${skip?'disabled':''}>✕ No válida</button></div>`}</article>`;}).join('')}</div><p class="hint">100 válida · 50 si se repite · +10 si alguien dejó esta categoría en blanco o en «No sé». No sé se puede revertir sin borrar lo escrito. La mayoría de votos negativos rechaza; un empate conserva la respuesta. Debe comenzar con ${esc(b.letter)}.</p><div class="dialog-actions"><button class="btn btn-primary" id="bach-reviewed">${b.reviewed.includes(state.me)?'✓ Revisión terminada':'Aceptar pendientes y terminar'}</button>${state.me===state.hostId?'<button class="btn btn-outline" id="bach-finish">Calcular puntos</button>':''}</div><p class="hint">${b.reviewed.length}/${state.players.length} revisiones terminadas. Los votos pendientes se aceptan al terminar tu revisión. Cierre automático a los 90 s.</p></section>`;
 root.querySelectorAll('[data-category]').forEach(btn=>btn.onclick=()=>{category=+btn.dataset.category;review();});root.querySelectorAll('[data-judge]').forEach(btn=>btn.onclick=()=>call({kind:'vote',player:btn.dataset.judge,column:category,valid:btn.dataset.valid==='true'}).catch(e=>toast(e.message)));$('#review-nose').onclick=()=>call({kind:'noSe',column:category}).catch(e=>toast(e.message));$('#bach-reviewed').onclick=()=>call({kind:'reviewed'}).catch(e=>toast(e.message));$('#bach-finish')?.addEventListener('click',()=>call({kind:'finish'}).catch(e=>toast(e.message)));
 }
 function scores(){const b=state.bach;$('#bach-status').textContent='Puntos revisados por el grupo. Todos ven el mismo marcador.';$('#bach-content').innerHTML=`<section class="panel"><div class="score-table-scroll"><table class="bach-table"><thead><tr><th>Jugador</th>${b.categories.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Ronda</th><th>Total</th></tr></thead><tbody>${[...(b.scoreRows||[])].sort((a,b)=>b.total-a.total).map(row=>`<tr><th>${esc(row.name)}</th>${row.cells.map(c=>`<td title="${esc(c.value)}"><b>${c.points}</b><small>${c.accepted?(c.duplicates>1?'Repetida':'Válida'):'0 puntos'}${c.bonus?' +10':''}</small></td>`).join('')}<td><b>${row.total}</b></td><td><b>${state.players.find(p=>p.id===row.id)?.score||0}</b></td></tr>`).join('')}</tbody></table></div><div class="dialog-actions">${state.me===state.hostId?'<button class="btn btn-primary" id="bach-next">'+(state.index+1===state.total?'Ver marcador final':'Siguiente letra')+' →</button>':'<p>Esperando al anfitrión…</p>'}</div></section>`;$('#bach-next')?.addEventListener('click',()=>send({type:'next'}).catch(e=>toast(e.message)));}
 timer=setInterval(()=>{if(!$('#bach-clock'))return;const end=phase==='bach-writing'?state.deadline:phase==='bach-review'?state.bach.reviewDeadline:0;$('#bach-clock').textContent=end?Math.max(0,Math.ceil((end-now())/1000))+'s':'';},100);update(state);return {update,destroy(){disposed=true;clearTimeout(debounce);clearInterval(timer);}};
}
